if (!require(devtools)){
  install.packages("devtools")
}
install.packages("oro.nifti")
install.packages("oro.dicom")
devtools::install_github("muschellij2/fslr")
devtools::install_github("stnava/ITKR")
devtools::install_github("stnava/ANTsR")
devtools::install_github("muschellij2/extrantsr")
install.packages("neurocInstall")
library(neurocInstall)
neuro_install(c("fslr", "neurohcp"), release = "stable")
neuro_install("ANTsR")
library(oro.dicom)
library(oro.nifti)
library(fslr)
library(ITKR)
library(ANTsR)
library(extrantsr)
